# fichier: flask-deployment.yaml
# Ce fichier cree deux ressources Kubernetes : un Deployment et un Service.
apiVersion: apps/v1
kind: Deployment # Un Deployment gere un ensemble de pods identiques
metadata:
  name: flask-api # Nom du Deployment (reference par ce nom)
  annotations:
    kubernetes.io/change-cause: "Update vers v2 - nouveau message"
    # Apparaitra dans l'historique des roolouts
spec:
  replicas: 3 # Nombre de copies (pods) au depart
  selector:
    matchLabels:
      app: flask-api # Le Deployment gere les pods ayant ce label
  strategy:
    type: RollingUpdate # Strategie de mise a jour progressive
    rollingUpdate:
      maxUnavailable: 1 # Max 1 pod indisponible pendant la mise a jour
      maxSurge: 1 # Max 1 pod supplementaire pendant la mise a jour
  template:
    metadata:
      labels:
        app: flask-api # Chaque pod cree aura ce label
    spec:
      containers:
      - name: flask-api
        image: nginx:alpine # Serveur web leger comme application de test
        ports:
        - containerPort: 80 # Le conteneur ecoute sur le port 80 (HTTP)
        env:
        - name: POD_NAME # Variable contenant le nom du pod
          valueFrom:
            fieldRef:
              fieldPath: metadata.name # Kubernetes injecte le nom du pod
        lifecycle:
          postStart: # Hook execute apres le demarrage du conteneur
            exec:
              command: ["/bin/sh", "-c",
                "echo 'VERSION 2 - Pod: '$(hostname) > /usr/share/nginx/html/index.html"]
                # Le message change : "VERSION 2" au lieu de "Hello depuis le pod"
                # C'est ce changement qui declenche le Rolling Update
        resources:
          requests: # Ressources minimum demandees
            cpu: "100m" # 100 millicores = 10% d'un coeur CPU
            memory: "64Mi" # 64 megaoctets de memoire
          limits: # Ressources maximum autorisees
            cpu: "250m" # 250 millicores = 25% d'un coeur CPU
            memory: "128Mi" # 128 megaoctets de memoire
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html # Volume pour la page HTML
      volumes:
        - name: html
          emptyDir: {} # Volume temporaire vide, partage dans le pod
